// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.FormResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Action/Adventure",
                            Director = "Joe Russo",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Avengers: Civil War",
                            Year = 2016
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Romance/Comedy",
                            Director = "Donald Petrie",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "How to Lose a Guy in 10 Days",
                            Year = 2003
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Action/Romance",
                            Director = "Aaron and Adam Nee",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Lost City",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
